# Generated by Django 4.0 on 2022-03-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('surname', models.CharField(max_length=30, verbose_name='surname')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('argument', models.CharField(max_length=50, verbose_name='argument')),
                ('content', models.TextField(verbose_name='content')),
                ('date_of_pub', models.DateField(verbose_name='date_of_publication')),
                ('auth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.author')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.category')),
                ('tags_id', models.ManyToManyField(to='API.Tag')),
            ],
        ),
    ]
