# Generated by Django 4.0.3 on 2022-03-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_pattern'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pattern',
        ),
    ]
