# Generated by Django 4.0.3 on 2022-03-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_delete_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='argument',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
